---
title: 'Study Guide: Test 1 - Chapter 1 Analysis of Biological Data 2nd ed.'
author: "brouwern@gmail.com"
date: "September 29, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 1. Statistics and Samples

### 1.1 What is statistics?

Vocab:

**Estimation:** The process of inferring an unknown quantity of a population using sample data. (pg 2)

**Parameters:** a quantity describing a population

**Estimate:** a quantity calcualted from a sample

### 1.2 Sampling populations

The concept of a statistical population and a biological population are different.  In statistics, it has a very very specific definition.

#### Example 1.2: Raining cats

Very important idea.  See page 9 for definition of **sample of convenience**.  An ecological example would be to use road-killed deer as a sample for estimating the size of deer horns.

#### Population and samples (pg 4)

Vocab:

**Population:** All individuals of interest

**Sample:** Subset of units taken from the population.

#### Properties of good samples (pg 5)

Vocab:

**Sampling error**

**Precision**

**Accurate (unbiased)**

**Bias**

**Figure 1.2-2** :The classic precision/bias bulls eye figure.

#### Random sampling

* Can't emphasize this enough!
* You must be able to distinguish a random from a non-random sample 
* You need to be able to determine if the study units are independent from each other or not

Vocab

*Random sample:*  "In a random sample, each member of a population has an equal and independent chance of being selected." (pg 7) Random means random.  If a random number generator wasn't involved in picking it, then it wasn't random!

*Equal chance:* Equal means equal.  Say I want to randomly sample all the students on campus to determine the mean age of CalU students.  I walk through the middle of campus and flip a coin each time I see someone.  If I get heads, I ask them their age; tails, I keep walking.  This involves randomness, *BUT* if I am interested in all the students at CalU then this sample is biased.  All student do not have an *"equal chance"* of being selected - I am only sampling students who are present on campus when I am collecting my data.

#### How to take a random sample

* Very important section

#### Figure 1.2-3

* Very important figure!

#### Sample of convience (pg 9)
#### Volunteer bias (pg 10)

Vocab:
**Sampline of convience**
**Volunteer Bias**

#### Data in the real world

### 1.3 Types of data an variables (pg 11)

* Based on answers on the homework, people seem to have trouble with this topic.  Doing practice problems can help.

Vocab:
**Variable:**  The characteristics being measured: length, height, weight, color, sex, etc.
**Data:** The actual measurements
**Categorical variable**
**Numeric variable**

#### Explantory and response variables

* People seem to have a very hard time with this. 
* In R we usually express things as "response ~ predictor"
* This reads as "the response depends on the predictor", or, the "response is caused by the predictor."
* We almost always plot things with the response on the y axis and predictor on the x.
* So, when trying to determine response vs. predictor, ask, "how would I plot this?"  Even better - draw a little graph and see if it makes sense.


## 1.4 Frequency distributions and probablity distributions (pg 13)

Vocab
**Frequency**
**Frequency distribution**

[we will talk about the normal distribution after the 1st test]

## 1.5 Types of studies

* People seem to struggle with this.
* "Observational study" doesn't mean "something was observed"; something always gets observed in a study or experiment however its done.  
* We use the word "observational" to indicate that *only* observations were made - the investigator did not do anything experimental; they did not manipulate, interfere, meddle, mess with, impact or change anything in any way.   
* In an observational study, all investigator does is observe the state of nature as it already was before they showed up; if the investigator was not there, things would be (largely) the same (the presence of an observer, however, can impact how things behave).
* In contrast, in an experiment, the investigator is actively and intentionally changing things.  In the investigator wasn't present, things would be completely different; in fact, often the investigator sets up everything that is being observed from scratch so without them there would be nothing going on at all.

Vocab

**Experimental study**  A study where the research "assigns different treatment groups or values of an explanatory variable randomly to the individuals units of study" (pg 15).  I often call this a "manipulative experiment" b/c the researcher is intentionally manipulating nature in order to answer the question they are interested in.

**Observational study** A study where the researcher has "no control over which units fall into which categories."  Observational studies are sometimes called "natural experiments" when nature has created experiment-like conditions.  A study documenting the reproductive rates of herons in an urban wetland would be purely observational.  A study comparing reproduction in urban wetlands with high levels of pollutants vs. rural wetlands would be a type of natural experiment.

## 1.6 Summary

Read it 

## Practice Problems

Do some! (or lots!)

